#include "game_constants.h"

const char *KEY_IMAGES[] = {BLUE_KEY, ORANGE_KEY, YELLOW_KEY, RED_KEY, PURPLE_KEY};
const rgba_color_t DOOR_COLORS[] = {COLOR_BLUE, COLOR_ORANGE, COLOR_YELLOW, COLOR_RED, COLOR_MAGENTA};
